### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by andarilhoz** [andarilhoz/slock-with-lasers#1]
I dont understand quite a lot of C language, neither the best practices from it.

So a cleanup on the slock.c because of my [commit](https://github.com/andarilhoz/slock-with-lasers/commit/361b4f5e136953acd0a08815d5a8c3e07cdc18ac) would be useful to make the code more understandable

**Comment by acabey** [comment]
Do you want logic to be cleaned up or just syntax and more general practices?

**Comment by andarilhoz** [comment]
@acabey  just syntax and general practices, the whole code its really simple, but the part i did is a little messed up (:

**Comment by acabey** [comment]
I'm not familiar enough with all of the X11 stuff going on here to be comfortable making any significant changes, but one suggestion I would make just for any C code going forward is using standardized types defined in `stdint.h`. Really you shouldn't be using any multi-word type identifiers anymore (such as `unsigned long long` ) and instead use the standard, fixed-width identifier ( `uint64_t` ). `char` in C is often misused and instead should generally be a `uint8_t`.

**Comment by andarilhoz** [comment]
[this](https://github.com/andarilhoz/slock-with-lasers/commit/361b4f5e136953acd0a08815d5a8c3e07cdc18ac#diff-1ec6d7c5dfe6b70bf1037c0d8f33e623) was the part i wanted some cleanup, but i just saw that @prprprpony already did it  on #5 (: i'll close this issue
