### ISSUE TITLE
Bugfix - make 5 photos taken at max

### ISSUE THREAD

**Issue by andarilhoz** [andarilhoz/slock-with-lasers#3]
Inside slock.c there are a few ifs where is the logic to take photos from camera, but sometimes it doesnt take 5 photos, other times it takes more..

Please refactor to take it at max 5 photos

**Comment by bvbfan** [comment]
https://github.com/andarilhoz/slock-with-lasers/pull/4

**Comment by andarilhoz** [comment]
@bvbfan thats alright, but, it still taking more or less photos, depending on type velocity

**Comment by andarilhoz** [comment]
@bvbfan  but, yah, its a start for what i asked (:

**Comment by pr3pony** [comment]
do you mean
take photo when someone entered a wrong password
if there are more than 5 wrong attempts, dont take photo

**Comment by andarilhoz** [comment]
Yes @prprprpony  but, if you type too fast the fswebcam cant take all the pictures, so, sometimes it only takes 1 or 2 pictures instead of 5, maybe it will affect the filename as well (the picture name is based on seconds and not mileseconds)

**Comment by pr3pony** [comment]
if someone has already tried more than 5 times, click ESC, and restart entering passwords
do you want to take another round of 5 photos?

**Comment by andarilhoz** [comment]
@prprprpony no, that would be a easy way to screw the HD xD

the whole purpose of these changes is prevent people from mess with the PC while is blocked, so, if it take endless photos would be a gap

buuut, that could be configurable in the future (: i could open a issue to that, thanks for the idea haha

**Comment by pr3pony** [comment]
#5 
did this solve the problem?

**Comment by andarilhoz** [comment]
I'll take a little bit longer to test it ( i have to reinstall linux on my notebook first) but in a few hours i'll test it (:

**Comment by pr3pony** [comment]
the problem is that you increase `mistakes` every keystroke excpet ESC
increase it only after the entered password is checked may solve the problem

**Comment by andarilhoz** [comment]
@prprprpony i tryed your PR, and didnt take any photo at all :/

the mistakes var is increased 'cause everytime someone types an screenshot without disableing the program (hiting esc 3x) it will take a screenshot

**Comment by pr3pony** [comment]
@andarilhoz 
I thought what you intended to do was to take photos when someone entered wrong passwords more than 3 times

**Comment by andarilhoz** [comment]
@prprprpony , sorry, but no, the idea is to take photos to every key hited, unless you hit espace before, i'll update the README to make that clear

**Comment by pr3pony** [comment]
But if you key in the right password, you'll still be shot, which doesn't make sense

**Comment by andarilhoz** [comment]
@prprprpony  after all, i think you are right, i'll just remove the condition where if mistakes was less then 4, cause that would make no sense too (:, thanks for the help, i'll mark this issue as closed
